version: '3'

services:

  logstash:
    command: /usr/share/plugins/plugin/scripts/logstash-run.sh
    environment:
      - INTEGRATION=${INTEGRATION:-false}


  integration:
    build:
      context: ../../
      dockerfile: scripts/opendistro/Dockerfile.opendistro
      args:
        - INTEGRATION=${INTEGRATION:-false}
    command: /usr/share/elasticsearch/elasticsearch-run.sh
    ports:
      - "9200:9200"
    user: elasticsearch
