FROM amazon/opendistro-for-elasticsearch:${OPENDISTRO_VERSION:-latest}

ARG es_path=/usr/share/elasticsearch
ARG SECURE_INTEGRATION

RUN if [ "$SECURE_INTEGRATION" != "true" ] ; then /usr/share/elasticsearch/bin/elasticsearch-plugin remove opendistro_security; fi
COPY --chown=elasticsearch:elasticsearch scripts/opendistro/elasticsearch-run.sh $es_path/
