FROM opensearchproject/opensearch:${OPENSEARCH_VERSION:-latest}

ARG plugin_path=/usr/share/plugins/plugin
ARG opensearch_path=/usr/share/opensearch
ARG opensearch_yml=$opensearch_path/config/opensearch.yml
ARG SECURE_INTEGRATION

RUN if [ "$SECURE_INTEGRATION" != "true" ] ; then echo "plugins.security.disabled: true" >> $opensearch_yml; fi
COPY --chown=opensearch:opensearch scripts/opensearch/opensearch-run.sh $opensearch_path/