version: '3'

services:

  logstash:
    command: /usr/share/plugins/plugin/scripts/logstash-run.sh
    environment:
      - INTEGRATION=true
      - SECURE_INTEGRATION=${SECURE_INTEGRATION:-false}
      - OPENSEARCH_VERSION=${OPENSEARCH_VERSION:-latest}

  integration:
    build:
      context: ../../
      dockerfile: scripts/opensearch/Dockerfile.opensearch
      args:
        - INTEGRATION=true
        - SECURE_INTEGRATION=${SECURE_INTEGRATION:-false}
        - OPENSEARCH_VERSION=${OPENSEARCH_VERSION:-latest}
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=myStrongPassword123!
    ports:
      - "9200:9200"
    user: opensearch
